# Generated by Django 5.2.5 on 2025-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='mobile number')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100, verbose_name='position')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('company_address', models.TextField(verbose_name='company address')),
            ],
        ),
    ]
