# Generated by Django 5.2.5 on 2025-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_size', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('number_of_openings', models.PositiveIntegerField()),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('any', 'Any Shift')], max_length=10)),
                ('job_type', models.CharField(choices=[('field', 'Field Job'), ('office', 'Office Job'), ('wfh', 'Work From Home'), ('industry', 'Industry Job')], max_length=10)),
                ('education_required', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('diploma', 'Diploma/ITI'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate'), ('none', 'Not Required')], max_length=20)),
                ('experience_required', models.CharField(choices=[('less_than_1', 'Less than 1 year'), ('1_3', '1-3 Years'), ('3_5', '3-5 Years'), ('5_10', '5-10 Years'), ('10_plus', '10+ Years'), ('any', 'Any Experience')], max_length=20)),
                ('preferred_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any Gender')], max_length=10)),
                ('skills_required', models.TextField(blank=True)),
                ('candidate_management', models.CharField(max_length=100)),
                ('terms_agreed', models.BooleanField(default=False)),
            ],
        ),
    ]
