# Generated by Django 5.2.5 on 2025-08-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='charges',
            field=models.BooleanField(default=False),
        ),
    ]
