# Generated by Django 5.2.5 on 2025-08-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_post_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='candidate_management',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='post',
            name='education_required',
        ),
        migrations.RemoveField(
            model_name='post',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preferred_gender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='post',
            name='terms_agreed',
        ),
    ]
