# Generated by Django 5.2.5 on 2025-08-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facility',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
