# Generated by Django 5.2.5 on 2025-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_post_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default='chakan', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='bus_route',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='calling_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='company_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='company_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='company_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1-2 Years', '1-2 Years'), ('3-5 Years', '3-5 Years'), ('5-10 Years', '5-10 Years'), ('10+ Years', '10+ Years')], default='fresher', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any Gender')], default='male', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='manage_data',
            field=models.CharField(choices=[('Calls', 'Calls'), ('WhatsApp', 'WhatsApp'), ('Apply', 'Apply'), ('Email', 'Email')], default='apply', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='min_education',
            field=models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Engineering', 'Engineering'), ('ITI', 'ITI'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('Uneducated', 'Uneducated')], default='10th', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='village',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_shift',
            field=models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('any', 'Any Shift')], default='three', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_title',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('field', 'Field Job'), ('office', 'Office Job'), ('wfh', 'Work From Home'), ('industry', 'Industry Job')], default='Field Job', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='min_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_of_openings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
