# Generated by Django 5.2.5 on 2025-08-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_post_area_post_bus_route_post_calling_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='facility',
            new_name='facilities',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='manage_data',
            new_name='manage_through',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='job_shift',
            new_name='shifts',
        ),
    ]
