# Generated by Django 5.2.5 on 2025-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_rename_facility_post_facilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_of_openings',
            new_name='number_of_opening',
        ),
        migrations.AddField(
            model_name='post',
            name='terms_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
