# Generated by Django 5.2.5 on 2025-08-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_rename_number_of_openings_post_number_of_opening_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_of_opening',
            new_name='number_of_openings',
        ),
    ]
