# Generated by Django 5.2.5 on 2025-08-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_rename_number_of_opening_post_number_of_openings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='manage_through',
            field=models.CharField(default='apply', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_salary',
            field=models.PositiveIntegerField(default=12000),
        ),
        migrations.AlterField(
            model_name='post',
            name='min_education',
            field=models.CharField(default='10th', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='min_salary',
            field=models.PositiveIntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='post',
            name='shifts',
            field=models.CharField(default='three', max_length=10),
        ),
    ]
