# Generated by Django 5.2.5 on 2025-08-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_post_manage_through_alter_post_max_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hr_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hr.hruser'),
        ),
    ]
