# Generated by Django 5.2.5 on 2025-08-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_post_hr_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bus_route',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
