# Generated by Django 5.2.5 on 2025-08-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_post_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('field', 'Field Job'), ('office', 'Office Job'), ('wfh', 'Work From Home'), ('industry', 'Industry Job')], default='Field Job', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='shifts',
            field=models.CharField(default='three', max_length=255),
        ),
    ]
