# Generated by Django 5.2.5 on 2025-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_post_job_type_alter_post_shifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='facilities',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
