# Generated by Django 5.2.5 on 2025-08-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_alter_post_course_name_alter_post_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course_name',
            field=models.CharField(blank=True, default='Any', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='facilities',
            field=models.CharField(blank=True, default='pf', max_length=255, null=True),
        ),
    ]
