# Generated by Django 5.2.5 on 2025-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_post_course_name_alter_post_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course_name',
            field=models.CharField(default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='facilities',
            field=models.CharField(default='pf', max_length=255),
        ),
    ]
