# Generated by Django 5.2.5 on 2025-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('Qualification', models.CharField(max_length=255)),
                ('current_address', models.TextField(blank=True)),
                ('Note', models.TextField(blank=True)),
            ],
        ),
    ]
