# Generated by Django 5.2.5 on 2025-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='Note',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='name',
        ),
        migrations.AddField(
            model_name='applications',
            name='course_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='applications',
            name='full_name',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='applications',
            name='mobile_number',
            field=models.CharField(default='None', max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='applications',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='age',
            field=models.PositiveIntegerField(default='None', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='current_address',
            field=models.TextField(default='None', verbose_name='Current Address'),
        ),
        migrations.AddField(
            model_name='applications',
            name='qualification',
            field=models.CharField(default='None', max_length=100, verbose_name='Qualification'),
        ),
    ]
