# Generated by Django 5.2.5 on 2025-08-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_alter_post_bus_route'),
        ('job', '0003_remove_applications_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr.post'),
        ),
    ]
